channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - adapterremoval=2.3.1
  - argparse=1.4.0
  - biopython=1.84
  - bowtie2=2.3.5.1
  - dedup=0.12.5
  - mamba=0.13.0
  - mapdamage2=2.2.1
  - numpy=2.0.0
  - pandas=2.2.2
  - picard=2.24.0
  - pip=19.3.1
  - psutil=5.7.2
  - pysam=0.16.0
  - python=3.9.19
  - pyyaml=5.4.1
  - r-gam=1.16.1
  - r-ggplot2=3.3.0
  - r-base=4.0.2
  - r-inline=0.3.15
  - r-rcpp=1.0.4.6
  - r-rcppgsl=0.3.8
  - requests=2.24.0
  - samtools=1.11
  - scipy=1.13.1
  - seqkit=0.13.2
  - seqtk=1.3
  - setuptools=49.6.0
  - snakemake=6.3.0
  - sra-tools=2.11.0
  - tbb=2020.2
  - wget=1.20.1
