#!/usr/bin/env python
# -*- coding: utf-8 -*-


# configfile: "config.yaml"


##### Modules #####


include: "rules/entrez.smk"


include: "rules/bowtie_index.smk"


include: "rules/bowtie_meta_index.smk"


include: "rules/entrez_custom_db.smk"


include: "rules/refseq.smk"


##### Wildcards #####


wildcard_constraints:
    query="[\w]+",
    sample="[\w]+",
    orgname="[^/]+",
    accession="[^/]+",
    chunk="\d+", # sample_accession="^(.(?!(_R1|_R2)))*."


##### Target rules #####


from datetime import datetime

startTime = datetime.now()


# rule all:
#     input:
# PE modern
# "refseq_rep/entrez/refseq_rep-invalid-assemblies.tsv",
# "fastq_inputs/PE_mod/SRR1031215_R1_adRm.fastq.gz",  # test adapterremoval.smk for merged ancient PE
# "refseq_rep/bowtie/refseq_rep_custom_seqs.fasta.gz",
# "refseq_rep/bowtie/refseq_rep_custom_acc.fasta.gz", # "refseq_rep/bowtie/refseq_rep_refseq_prok.fasta.gz", # test refseq.smk
# "refseq_rep/bowtie/refseq_rep_entrez.fasta.gz", # test entrez.smk,
# "refseq_rep/fastq/PE/SRR1031215_mapq_pair.readlen", # test bowtie.smk
# "refseq_rep/sigma/SRR1031215_alignments.done",   # test bowtie_meta.smk,
# "refseq_rep/probabilities/SRR1031215/SRR1031215_posterior_probabilities.csv", #test metagenomics.smk - probabilities
# "refseq_rep/probabilities/SRR1031215/SRR1031215_posterior_abundance.tsv", #test metagenomics.smk - abundances
# "refseq_rep/mapdamage/SRR1031215_mapdamage.done" # test mapdamage.smk
# PE ancient
# "fastq_inputs/PE_anc/SRR1031289_adRm.fastq.gz", # test adapterremoval.smk for merged ancient PE
# "refseq_rep/bowtie/refseq_rep_refseq_prok.fasta.gz", # test refseq.smk
# "refseq_rep/bowtie/refseq_rep_entrez.fasta.gz", # test entrez.smk,
# "refseq_rep/fastq/SE/SRR1031289_mapq.readlen", # test bowtie.smk
# "refseq_rep/sigma/SRR1031289_alignments.done",   # test bowtie_meta.smk
# "refseq_rep/probabilities/SRR1031289/SRR1031289_posterior_probabilities.csv", #test metagenomics.smk - probabilities
# "refseq_rep/probabilities/SRR1031289/SRR1031289_posterior_abundance.tsv", #test metagenomics.smk - abundances
# "refseq_rep/mapdamage/SRR1031289_mapdamage.done" # test mapdamage.smk
# SE
# "fastq_inputs/SE/SRR054920_adRm.fastq.gz",  # test adapterremoval.smk for ancient SE
# "refseq_rep/bowtie/refseq_rep_refseq_prok.fasta.gz",  # test refseq.smk
# "refseq_rep/bowtie/refseq_rep_entrez.fasta.gz",  # test entrez.smk
# "refseq_rep/fastq/SE/SRR054920_mapq.readlen",  # test bowtie.smk
# "refseq_rep/sigma/SRR054920_alignments.done",  # test bowtie_meta.smk
# "refseq_rep/probabilities/SRR054920/SRR054920_posterior_probabilities.csv",
# #test metagenomics.smk - probabilities
# "refseq_rep/probabilities/SRR054920/SRR054920_posterior_abundance.tsv",  #test metagenomics.smk - abundances
# "refseq_rep/mapdamage/SRR054920_mapdamage.done" # test mapdamage.smk


# "refseq_rep/bowtie/refseq_rep_refseq_prok.fasta.gz", # test refseq.smk
# "refseq_rep/bowtie/refseq_rep_entrez.fasta.gz", # test entrez.smk
# "refseq_rep/fastq/RISE00_mapq.readlen",  # test bowtie.smk
# "refseq_rep/sigma/RISE00_alignments.done",   # test bowtie_meta.smk
# "refseq_rep/probabilities/RISE00/RISE00_posterior_probabilities.csv", #test metagenomics.smk - probabilities
# "refseq_rep/probabilities/RISE00/RISE00_posterior_abundance.tsv" #test metagenomics.smk - abundances
# "yersinia_test/entrez_alt/sizes.txt",

# "yersinia_test/bowtie/yersinia_test.fasta.gz",  # test entrez.smk
# "yersinia_test/fastq/RISE00_mapq.readlen",      # test bowtie.smk
# "yersinia_test/sigma/RISE00_alignments.done",   # test bowtie_meta.smk
# "yersinia_test/probabilities/RISE00/RISE00_posterior_probabilities.csv", #test metagenomics.smk - probabilities
# "yersinia_test/probabilities/RISE00/RISE00_posterior_abundance.tsv" #test metagenomics.smk - abundances

print(datetime.now() - startTime)
