#!/usr/bin/env python
# -*- coding: utf-8 -*-


# configfile: "config.yaml"


##### Modules #####


include: "rules/metagenomics.smk"


include: "rules/adapterremoval.smk"


include: "rules/sra.smk"


##### Wildcards #####


wildcard_constraints:
    query="[\w]+",
    sample="[\w]+",
    orgname="[^/]+",
    accession="[^/]+",
    chunk="\d+", # sample_accession="^(.(?!(_R1|_R2)))*."


##### Target rules #####


from datetime import datetime

startTime = datetime.now()

print(datetime.now() - startTime)
